version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Web-app
hooks:
  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
